development:
  adapter: postgresql
  encoding: unicode
  database: production
  pool: 5
  username: postgres
  password: password

development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: postgres
  password: password
